import type { Metadata, NextPage } from 'next'
import type { PropsWithChildren } from 'react';
import '@/styles/globals.css';

export const metadata: Metadata = {
  title: 'My Next Toy App',
  description: 'Generated by create next app',
}

const RootLayout: NextPage<PropsWithChildren> = ({ children }) => {
  
    return (
        <html lang='en'>
            <body>
                <div className='background'>
                    <div className='gradient' />
                </div>
                <main className='app'>
                    {children}
                </main>
            </body>
        </html>
    );
}

export default RootLayout;