import type { Metadata, NextPage } from 'next'
import type { PropsWithChildren } from 'react';
import { ToastContainer } from 'react-toastify';
import Header from '@/components/features/Header';
import AuthProvider from '@/components/features/AuthProvider';
import '@/styles/globals.css';
import PostProvider from '@/context/PostProvider';

export const metadata: Metadata = {
  title: 'My Next Post App',
  description: 'Generated by create next app',
}

const RootLayout: NextPage<PropsWithChildren> = ({ children }) => {

    return (
        <html lang='en'>
            <body>
                <AuthProvider>
                    <PostProvider>
                        <div className='background'>
                            <div className='gradient' />
                        </div>
                        <div className='app'>
                            <Header />
                            {children}
                        </div>
                        <ToastContainer />
                    </PostProvider>                    
                </AuthProvider>
            </body>
        </html>
    );
}

export default RootLayout;